basePath: /api
definitions:
  types.Artist:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      mbid:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  types.UserLoginPayload:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  types.UserRegisterPayload:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        maxLength: 130
        minLength: 3
        type: string
    required:
    - email
    - name
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for Concert Tracker.
  title: Concert Tracker API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Returns a simple Hello World message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Home Route
      tags:
      - Home
  /artist:
    get:
      description: Gets information for requested artist. If information does not
        exist in database, it is retrieved from setlist.fm API and entered into database
      parameters:
      - description: Artist Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Object that holds artist information
          schema:
            $ref: '#/definitions/types.Artist'
        "400":
          description: Error describing failure
          schema:
            type: string
      summary: Serve information for a given artist
      tags:
      - Artist
  /import:
    get:
      description: Gets setlist information from setlist.fm API for given artist,
        and imports it into database
      parameters:
      - description: Artist MBID
        in: path
        name: mbid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Message indicating success
          schema:
            type: string
        "400":
          description: Error describing failure
          schema:
            type: string
      summary: Import information for a given artist into database
      tags:
      - Artist
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token
      parameters:
      - description: Login Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.UserLoginPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid email or password
          schema:
            type: string
      summary: Login user
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Registers a new user
      parameters:
      - description: Register Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.UserRegisterPayload'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            type: string
        "400":
          description: Invalid payload or user already exists
          schema:
            type: string
      summary: Register user
      tags:
      - Auth
  /validate:
    get:
      description: Verifies if a user's session cookie contains an authenticated token
      produces:
      - application/json
      responses:
        "200":
          description: user session validated
          schema:
            type: string
        "401":
          description: missing or invalid authorization token
          schema:
            type: string
      summary: Validate user session
      tags:
      - Auth
schemes:
- http
swagger: "2.0"
